export const continents = [
    {
        '_id':1,
        'name':'Asia'
    },
    {
        '_id':2,
        'name':'Europe'
    },
    {
        '_id':3,
        'name':'Africa'
    },
    {
        '_id':4,
        'name':'Australia'
    },
    {
        '_id':5,
        'name':'North America'
    },
    {
        '_id':6,
        'name':'South America'
    },
    {
        '_id':7,
        'name':'Antarctica'
    }
]
export const price = [
    {
        '_id':0,
        'name':'상관없음',
        'array':[]
    },
    {
        '_id':1,
        'name':'0~10만원',
        'array':[0,99999]
    },
    {
        '_id':2,
        'name':'10~20만원',
        'array':[100000,199999]
    },
    {
        '_id':3,
        'name':'20~30만원',
        'array':[200000,299999]
    },
    {
        '_id':4,
        'name':'30~40만원',
        'array':[300000,399999]
    },
    {
        '_id':5,
        'name':'40만원 이상',
        'array':[400000,15000000]
    }
]